"""Tier 1 chapters: survival basics, andesite Create, exploration."""
from lib import register_chapter, I, K, CK, R, XP, LV

T1 = 0x20000

# ── t1_survival ──────────────────────────────────────────────────────────────
register_chapter("t1_survival", 0x21000, T1, 0, "First Steps", "minecraft:campfire", [
    dict(n=1, title="Welcome to Gaia", icon="minecraft:crafting_table", x=0.0, y=0.0,
         sub="You punch a tree. Classy.",
         desc=["Welcome to Gaia Awakening! This world is taller, wilder and far more dangerous than vanilla.",
               "Your first move? Punch a tree. It's tradition at this point.",
               "Open your quest book anytime to see what's next. Diamond-shaped quests are optional side content with juicy rewards."],
         tasks=[I("minecraft:crafting_table"), I("minecraft:oak_log")],
         rewards=[R("minecraft:stone_pickaxe"), R("minecraft:stone_axe"), R("minecraft:apple", 3), XP(50)]),
    dict(n=2, title="Fire and Ore", icon="minecraft:furnace", x=0.0, y=1.5,
         sub="Heat rocks until they cry. It works.", deps=[1],
         desc=["Step one of civilization: shove things into fire until something useful comes out.",
               "Build a furnace and smelt some iron. You will need a LOT of it later — trust us."],
         tasks=[I("minecraft:furnace"), I("minecraft:iron_ingot", 8)],
         rewards=[R("minecraft:coal", 8), XP(75)]),
    dict(n=3, title="Iron Will", icon="minecraft:iron_chestplate", x=0.0, y=3.0,
         sub="Mobs don't care about your feelings.", deps=[2],
         desc=["Night is coming. Skeletons have bows. You have a wooden sword. This is not a fair fight.",
               "Craft a full set of iron armor — helmet, chestplate, leggings, boots. No partial credit."],
         tasks=[I("minecraft:iron_helmet"), I("minecraft:iron_chestplate"),
                I("minecraft:iron_leggings"), I("minecraft:iron_boots")],
         rewards=[R("minecraft:golden_apple", 2), R("minecraft:emerald", 4), XP(100)]),
    dict(n=4, title="A Place to Sleep", icon="minecraft:red_bed", x=-1.5, y=1.5,
         sub="Phantoms are watching.", deps=[1], optional=True, shape="diamond",
         desc=["Craft a bed and set your spawn. The world is huge — dying 3000 blocks from home is a lesson you only need once."],
         tasks=[I("minecraft:white_bed")],
         rewards=[R("minecraft:torch", 32), XP(25)]),
    dict(n=5, title="Farm to Table", icon="farmersdelight:cooking_pot", x=-1.5, y=3.0,
         sub="Bread is a personality trait.", deps=[2], optional=True, shape="diamond",
         desc=["Farmer's Delight adds proper cooking. Craft a Cooking Pot and a Stove, then cook real meals.",
               "Good food gives the Nourishment buff — better saturation than vanilla snacks."],
         tasks=[I("farmersdelight:cooking_pot"), I("farmersdelight:stove")],
         rewards=[R("minecraft:golden_carrot", 8), R("farmersdelight:rich_soil", 16), XP(75)]),
    dict(n=6, title="Seasons Change", icon="minecraft:clock", x=-3.0, y=3.0,
         sub="Winter is coming. Literally.", deps=[5], optional=True, shape="diamond",
         desc=["Serene Seasons is active: crops only grow in their fertile seasons!",
               "Craft a Calendar to track the current season. Plan your farms accordingly — or use greenhouse glass."],
         tasks=[I("sereneseasons:calendar")],
         rewards=[R("minecraft:bone_meal", 32), XP(50)]),
    dict(n=7, title="Diamonds!", icon="minecraft:diamond", x=0.0, y=4.5,
         sub="Shiny rocks that make better rocks.", deps=[3],
         desc=["Diamonds don't hide in the stone here — you pull them from diamond veins with a Crystal Drill Head (see Veins of Gaia).",
               "For your first few, raid dungeons and trade with villagers. The drill handles the rest later."],
         tasks=[I("minecraft:diamond", 3)],
         rewards=[R("minecraft:tnt", 4), XP(100)]),
    dict(n=8, title="Enchanted", icon="minecraft:enchanting_table", x=0.0, y=6.0,
         sub="Bibliophile with benefits.", deps=[7],
         desc=["Build an Enchanting Table. Apotheosis overhauls the whole system — more shelves, more stats, better results.",
               "Later, our custom pressure-enchanting system will push enchantments far beyond vanilla limits."],
         tasks=[I("minecraft:enchanting_table"), I("minecraft:bookshelf", 15)],
         rewards=[R("minecraft:lapis_lazuli", 32), R("minecraft:experience_bottle", 8), XP(100)]),
    dict(n=9, title="Claim Your Land", icon="minecraft:filled_map", x=1.5, y=1.5,
         sub="Mine! All mine!", deps=[1], optional=True, shape="diamond",
         desc=["Open the map (press M) and claim chunks with FTB Chunks. Claimed chunks are protected from other players and explosions.",
               "JourneyMap (press J) gives you the full world map and waypoints."],
         tasks=[CK("Claim at least one chunk")],
         rewards=[R("minecraft:ender_pearl", 4), XP(50)]),
    dict(n=10, title="One Block? All Blocks!", icon="minecraft:iron_pickaxe", x=1.5, y=3.0,
         sub="Hold the magic button.", deps=[3], optional=True, shape="diamond",
         desc=["FTB Ultimine: hold the grave key (`) while mining to break a whole rock face, chop a whole tree or harvest a whole field at once.",
               "It costs hunger, so keep snacks around."],
         tasks=[CK("Use Ultimine to fell a tree")],
         rewards=[R("minecraft:cooked_beef", 16), XP(50)]),
    dict(n=11, title="Pack Mule", icon="sophisticatedbackpacks:backpack", x=1.5, y=4.5,
         sub="Pockets. Lots of pockets.", deps=[7], optional=True, shape="diamond",
         desc=["Sophisticated Backpacks are upgradeable inventories you wear. Craft one, then add upgrades like magnets, feeding or auto-smelting.",
               "This reward magnet upgrade alone is worth the detour."],
         tasks=[I("sophisticatedbackpacks:backpack")],
         rewards=[R("sophisticatedbackpacks:magnet_upgrade"), XP(100)]),
    dict(n=12, title="Set a Waypoint Home", icon="waystones:waystone", x=0.0, y=7.5,
         sub="Fast travel unlocked.", deps=[8],
         desc=["Craft a Waystone and place it at your base. Activate any Waystone you find in villages or dungeons to teleport between them.",
               "The world is enormous — this is how you survive it."],
         tasks=[I("waystones:waystone")],
         rewards=[R("minecraft:ender_pearl", 8), XP(100)]),
    dict(n=13, title="Into Hell", icon="minecraft:obsidian", x=0.0, y=9.0,
         sub="What could possibly go wrong?", deps=[12],
         desc=["Build a Nether portal. You need Nether resources for what comes next: quartz for machines, blaze rods for brass.",
               "Bring fire resistance. Seriously."],
         tasks=[I("minecraft:obsidian", 10), I("minecraft:flint_and_steel")],
         rewards=[R("minecraft:golden_apple", 2), XP(150)]),
    dict(n=14, title="Blaze It", icon="minecraft:blaze_rod", x=0.0, y=10.5,
         sub="Number one import: angry fire men.", deps=[13],
         desc=["Hunt blazes in a Nether fortress. Blaze rods power the Blaze Burners you need for the Brass Age.",
               "Quartz no longer hides in nether rock — you'll drill it from quartz veins with a Reinforced Drill Head (see Veins of Gaia)."],
         tasks=[I("minecraft:blaze_rod", 4), I("minecraft:quartz", 16)],
         rewards=[R("minecraft:blaze_rod", 4), R("minecraft:obsidian", 8), XP(200)]),
])

# ── t1_create ────────────────────────────────────────────────────────────────
register_chapter("t1_create", 0x22000, T1, 1, "The Andesite Age", "create:cogwheel", [
    dict(n=1, title="Andesite Alloy", icon="create:andesite_alloy", x=0.0, y=0.0,
         sub="The cornerstone of engineering.",
         desc=["Create is the heart of this pack. Everything starts with Andesite Alloy: andesite plus iron or zinc nuggets.",
               "Make a stack — you will burn through it faster than you think."],
         tasks=[I("create:andesite_alloy", 8)],
         rewards=[R("create:andesite_alloy", 8), XP(50)]),
    dict(n=2, title="Shafts and Cogs", icon="create:cogwheel", x=1.5, y=0.0,
         sub="Spin to win.", deps=[1],
         desc=["Shafts carry rotation, cogwheels redirect it and change speed. This is the language of Create — learn it well.",
               "Ponder any Create block (hover + W) for an interactive 3D tutorial!"],
         tasks=[I("create:shaft", 8), I("create:cogwheel", 8)],
         rewards=[R("create:large_cogwheel", 4), XP(50)]),
    dict(n=3, title="Water Power", icon="create:water_wheel", x=3.0, y=0.0,
         sub="Hydroelectric, sort of.", deps=[2],
         desc=["Water Wheels are your first power source. Place them in flowing water — more flow faces, more speed.",
               "Stress is Create's power budget: generators add capacity, machines consume it. Goggles show the numbers."],
         tasks=[I("create:water_wheel", 3)],
         rewards=[R("minecraft:bucket", 2), XP(75)]),
    dict(n=4, title="Engineer's Toolkit", icon="create:goggles", x=3.0, y=-1.5,
         sub="Safety third.", deps=[2], optional=True, shape="diamond",
         desc=["The Wrench rotates and picks up machines. Goggles show stress, speed and capacity when you look at components.",
               "No engineer leaves home without them."],
         tasks=[I("create:wrench"), I("create:goggles")],
         rewards=[R("create:clipboard"), XP(75)]),
    dict(n=5, title="Press On", icon="create:mechanical_press", x=4.5, y=0.0,
         sub="Flat is a feature.", deps=[3],
         desc=["The Mechanical Press flattens ingots into sheets and compacts blocks in a Basin below it.",
               "Iron sheets are everywhere in Create recipes — automate this early."],
         tasks=[I("create:mechanical_press"), I("create:depot")],
         rewards=[R("create:iron_sheet", 16), XP(100)]),
    dict(n=6, title="Mixing It Up", icon="create:mechanical_mixer", x=4.5, y=1.5,
         sub="Stir vigorously.", deps=[5],
         desc=["Mixer plus Basin combines ingredients automatically. With a Blaze Burner below it can even smelt mixtures — remember that for brass!"],
         tasks=[I("create:mechanical_mixer"), I("create:basin")],
         rewards=[R("minecraft:copper_ingot", 16), XP(100)]),
    dict(n=7, title="Crushing It", icon="create:crushing_wheel", x=6.0, y=0.0,
         sub="Rocks go in. Better rocks come out.", deps=[5],
         desc=["Two Crushing Wheels spinning toward each other pulverize anything dropped between them.",
               "Crushed raw ores can be washed for bonus output — this is your ore doubling!"],
         tasks=[I("create:crushing_wheel", 2)],
         rewards=[R("minecraft:raw_gold", 12), XP(125)]),
    dict(n=8, title="Double Your Ores", icon="create:crushed_raw_iron", x=6.0, y=1.5,
         sub="Free real estate.", deps=[7], optional=True, shape="diamond",
         desc=["Crush raw iron into crushed ore, then wash it with an Encased Fan blowing through water for nuggets and bonus drops.",
               "Set this up once and never waste a raw ore again."],
         tasks=[I("create:crushed_raw_iron", 16)],
         rewards=[R("minecraft:raw_iron", 32), R("minecraft:raw_copper", 32), XP(150)]),
    dict(n=9, title="Belts and Funnels", icon="create:andesite_funnel", x=7.5, y=0.0,
         sub="The conveyor lifestyle.", deps=[7],
         desc=["Belts move items between machines, funnels load and unload them. This is how factories are born.",
               "Combine with Depots and you can automate nearly every Create process."],
         tasks=[I("create:belt_connector", 4), I("create:andesite_funnel", 4)],
         rewards=[R("create:belt_connector", 8), XP(100)]),
    dict(n=10, title="Smart Logistics", icon="create:filter", x=7.5, y=1.5,
         sub="Sorting hat, industrial edition.", deps=[9], optional=True, shape="diamond",
         desc=["Filters attach to funnels and tunnels to sort items. Brass tunnels later split belts into entire sorting systems."],
         tasks=[I("create:filter", 2)],
         rewards=[R("minecraft:redstone", 16), XP(75)]),
    dict(n=11, title="Andesite Casing", icon="create:andesite_casing", x=9.0, y=0.0,
         sub="Graduation, part one.", deps=[9],
         desc=["Andesite Casings are the chassis of the early Create age. With these you have mastered Tier 1 engineering.",
               "Next stop: the Brass Age — but you'll need blaze rods from the Nether first."],
         tasks=[I("create:andesite_casing", 8)],
         rewards=[R("create:andesite_alloy", 32), XP(150)]),
    dict(n=12, title="Windmill", icon="create:windmill_bearing", x=3.0, y=1.5,
         sub="Don Quixote was onto something.", deps=[3], optional=True, shape="diamond",
         desc=["A Windmill Bearing with at least 8 sail blocks gives you slow but STRONG rotation — way more stress capacity than water wheels.",
               "Build it big. Build it beautiful."],
         tasks=[I("create:windmill_bearing"), I("create:white_sail", 8)],
         rewards=[R("create:white_sail", 16), XP(125)]),
])

# ── t1_exploration ───────────────────────────────────────────────────────────
register_chapter("t1_exploration", 0x23000, T1, 2, "Into the Wild", "naturescompass:naturescompass", [
    dict(n=1, title="Nature's Compass", icon="naturescompass:naturescompass", x=0.0, y=0.0,
         sub="Which way to the jungle?",
         desc=["This world mixes Tectonic and Terralith — over 100 biomes, towering peaks up to Y=512 and underground rivers.",
               "Nature's Compass locates any biome. Craft it and go sightseeing."],
         tasks=[I("naturescompass:naturescompass")],
         rewards=[R("minecraft:map", 2), XP(75)]),
    dict(n=2, title="Explorer's Compass", icon="explorerscompass:explorerscompass", x=1.5, y=0.0,
         sub="Which way to the loot?", deps=[1],
         desc=["The Explorer's Compass finds STRUCTURES: dungeons, strongholds, witch huts, bastions and everything modded.",
               "When Dungeons Arise structures are massive — bring supplies and a sword."],
         tasks=[I("explorerscompass:explorerscompass")],
         rewards=[R("minecraft:ender_eye", 2), XP(100)]),
    dict(n=3, title="Finders Keepers", icon="minecraft:chest", x=0.0, y=1.5,
         sub="Your loot is YOUR loot.", deps=[1], optional=True, shape="diamond",
         desc=["Lootr makes every loot chest per-player — teammates can open the same chest and get their own loot. No more ninja-looting!",
               "Loot any naturally generated chest to complete this."],
         tasks=[CK("Open a Lootr chest")],
         rewards=[R("minecraft:golden_apple", 2), XP(75)]),
    dict(n=4, title="Artifact Hunter", icon="minecraft:totem_of_undying", x=1.5, y=1.5,
         sub="Museum-grade equipment.", deps=[2], optional=True, shape="diamond",
         desc=["Artifacts hide in dungeon loot and special structures: night-vision goggles, cloud step boots, lucky scarves and more.",
               "They go into your Curios slots (press G to view). Find one!"],
         tasks=[CK("Find any Artifact")],
         rewards=[R("minecraft:diamond", 4), XP(150)]),
    dict(n=5, title="Dungeon Delver", icon="minecraft:skeleton_skull", x=3.0, y=1.5,
         sub="It's a trap. Go anyway.", deps=[2], optional=True, shape="diamond",
         desc=["When Dungeons Arise spawns colossal structures: flying ships, fortified castles, jungle temples.",
               "Clear one out. The loot is excellent — and so are the ambushes."],
         tasks=[CK("Raid a large dungeon structure")],
         rewards=[R("minecraft:enchanted_golden_apple"), R("minecraft:diamond", 4), XP(200)]),
    dict(n=6, title="Ferrous Wroughtnaut", icon="minecraft:iron_block", x=3.0, y=0.0,
         sub="It only moves when you do. Wait, no, it always moves.", deps=[2],
         desc=["Your first real boss: Mowzie's Ferrous Wroughtnaut waits in underground chambers.",
               "Attack its back when it gets stuck after a swing. Patience beats panic."],
         tasks=[K("mowziesmobs:ferrous_wroughtnaut")],
         rewards=[R("minecraft:diamond", 6), LV(5)]),
    dict(n=7, title="Frostmaw", icon="minecraft:packed_ice", x=4.5, y=0.0,
         sub="A very good boy. A very ANGRY good boy.", deps=[6], optional=True, shape="diamond",
         desc=["The Frostmaw guards an ice crystal in frozen biomes. It hits like a truck and freezes you solid.",
               "Bring fire, patience and a backup plan. The Ice Crystal reward is a powerful weapon."],
         tasks=[K("mowziesmobs:frostmaw")],
         rewards=[R("minecraft:diamond_block", 2), LV(10)]),
    dict(n=8, title="Waystone Network", icon="waystones:waystone", x=0.0, y=-1.5,
         sub="Public transport, medieval edition.", deps=[1], optional=True, shape="diamond",
         desc=["Place Waystones at key locations: your mine, the village, that one mountain with the view.",
               "A good network turns a 4000-block trek into a click."],
         tasks=[I("waystones:waystone", 3)],
         rewards=[R("minecraft:ender_pearl", 16), XP(150)]),
])

# ── t1_veins ──────────────────────────────────────────────────────────────────
register_chapter("t1_veins", 0x24000, T1, 2, "Veins of Gaia", "create:crimsite", [
    dict(n=1, title="The Crimson Truth", icon="create:crimsite", x=0.0, y=0.0,
         sub="Your iron isn't where you left it.",
         desc=["Bad news: ore doesn't spawn in the stone here. Swing a pickaxe at a cave wall all day and you'll get cobblestone and regret.",
               "Good news: metal comes from two new places. Early on, Create's coloured stones. Later, the Drilling Machine taps deep ore veins.",
               "This chapter is your map from a fistful of raw iron to an automated ore empire."],
         tasks=[CK("Read on, prospector")],
         rewards=[XP(50)]),
    dict(n=2, title="Bleeding Stone", icon="minecraft:raw_iron", x=0.0, y=1.5, deps=[1],
         sub="Red rock, raw iron.",
         desc=["Crimsite is the blood-red stone streaked through the world. Mine it, drop it between two Crushing Wheels, and it bleeds Raw Iron.",
               "You cannot craft these stones — that recipe is gone. They must be mined. This is your only metal until the drill is built."],
         tasks=[I("create:crimsite", 16), I("minecraft:raw_iron", 8)],
         rewards=[R("minecraft:raw_iron", 8), XP(75)]),
    dict(n=3, title="The Full Palette", icon="minecraft:raw_gold", x=0.0, y=3.0, deps=[2],
         sub="Four stones, four metals.",
         desc=["The other three coloured stones crush just like Crimsite: Veridium gives Copper, Ochrum gives Gold, Asurine gives Zinc.",
               "Stockpile all four metals — the Drilling Machine and its first bit are hungry for iron and brass parts."],
         tasks=[I("minecraft:raw_copper", 8), I("minecraft:raw_gold", 4), I("create:raw_zinc", 8)],
         rewards=[R("minecraft:raw_gold", 6), XP(100)]),
    dict(n=4, title="Stop Digging, Start Drilling", icon="createoreexcavation:drilling_machine", x=0.0, y=4.5, deps=[3],
         sub="The machine eats stone. You eat ingots.",
         desc=["The Drilling Machine is the heart of this pack's ore game. Build it: 7 Iron Blocks, a Precision Mechanism and a Brass Casing.",
               "It needs Brass — so this is your push into the Brass Age. You'll power it with Create rotation."],
         tasks=[I("createoreexcavation:drilling_machine")],
         rewards=[R("create:precision_mechanism"), XP(150)]),
    dict(n=5, title="Basic Instinct", icon="gaia:basic_drill_head", x=0.0, y=6.0, deps=[4],
         sub="Your first bit.",
         desc=["A Drilling Machine without a bit just hums. Craft the Basic Drill Head and slot it in.",
               "The Basic head handles Tier 1 veins: iron, copper and coal. Everything deeper needs a tougher bit."],
         tasks=[I("gaia:basic_drill_head")],
         rewards=[XP(100)]),
    dict(n=6, title="Strike Iron", icon="minecraft:iron_ingot", x=0.0, y=7.5, deps=[5],
         sub="Stone goes in, ingots come out.",
         desc=["Find a vein with the Ore Vein Finder or the Prospector's Radar, sit the machine on top, and feed it rotation.",
               "Veins are FINITE — each one drains dry, then you move on. The world is full of them, so go prospecting.",
               "Let the machine do the mining and pull out a stack of raw iron."],
         tasks=[I("minecraft:raw_iron", 32)],
         rewards=[R("createoreexcavation:vein_finder"), XP(150)]),
    dict(n=7, title="Reinforcements", icon="gaia:reinforced_drill_head", x=0.0, y=9.0, deps=[6],
         sub="Tougher bit, richer veins.",
         desc=["The Reinforced Drill Head (Tier 2) cracks open a whole new shopping list: gold, zinc, redstone, lapis, osmium, tin, lead, silver, nether quartz and inferium.",
               "Osmium and nether quartz cap at this tier on purpose — you need them to build the fancier bits."],
         tasks=[I("gaia:reinforced_drill_head")],
         rewards=[XP(150)]),
    dict(n=8, title="Osmium Bit", icon="gaia:osmium_drill_head", x=-1.5, y=10.5, deps=[7],
         sub="Glowing green payday.",
         desc=["The Osmium Drill Head (Tier 3) reaches the radioactive shelf: uranium and fluorite.",
               "Handle uranium with care — Mekanism radiation is no joke."],
         tasks=[I("gaia:osmium_drill_head")],
         rewards=[XP(200)]),
    dict(n=9, title="Hellfire Bit", icon="gaia:nether_drill_head", x=0.0, y=10.5, deps=[7],
         sub="Bring fire resistance.",
         desc=["The Nether Drill Head (Tier 3) works the hot rocks: nether gold, glowstone and ancient debris.",
               "Yes — this is how you farm netherite now. Set up shop in the Nether."],
         tasks=[I("gaia:nether_drill_head")],
         rewards=[XP(200)]),
    dict(n=10, title="Crystal Bit", icon="gaia:crystal_drill_head", x=1.5, y=10.5, deps=[7],
         sub="Shiny rocks that make better rocks.",
         desc=["The Crystal Drill Head (Tier 3) cuts gem veins: diamond, emerald and Mystical Agriculture prosperity.",
               "Diamonds are a drill away now — no more digging blind below Y=16."],
         tasks=[I("gaia:crystal_drill_head")],
         rewards=[XP(200)]),
    dict(n=11, title="Obsidian Bit", icon="gaia:refined_obsidian_drill_head", x=0.0, y=12.0, deps=[8, 9, 10],
         sub="Endgame metals.",
         desc=["The Refined Obsidian Drill Head (Tier 4) reaches the deepest veins: thorium and uraninite — the fuel of the late-game power chains.",
               "Refined Obsidian itself is a Mekanism endgame material. You've come a long way from crushing red rocks."],
         tasks=[I("gaia:refined_obsidian_drill_head")],
         rewards=[XP(300)]),
    dict(n=12, title="Gaia-Infused Bit", icon="gaia:gaia_infused_drill_head", x=0.0, y=13.5, deps=[11],
         sub="The apex bit.",
         desc=["The Gaia-Infused Drill Head is the pinnacle: the best yields, a chance at a Resource Catalyst byproduct, and the only bit that taps the rarest deposits.",
               "Every vein in the world is now yours for the taking."],
         tasks=[I("gaia:gaia_infused_drill_head")],
         rewards=[R("gaia:resource_catalyst", 2), XP(500)]),
    dict(n=13, title="Salty Boost", icon="mekanism:rotary_condensentrator", x=-1.5, y=7.5, deps=[6], optional=True, shape="diamond",
         sub="Season your mining.",
         desc=["Pipe Mekanism Brine through a Rotary Condensentrator to turn it into a fluid, then pump it into the Drilling Machine.",
               "A fed machine drills richer — about 50% more ore per cycle. Keep the brine flowing, or it falls back to dry output."],
         tasks=[CK("Boost a Drilling Machine with brine")],
         rewards=[XP(150)]),
    dict(n=14, title="Multiply", icon="mekanism:purification_chamber", x=1.5, y=7.5, deps=[6], optional=True, shape="diamond",
         sub="One raw, sixteen ingots.",
         desc=["Raw ore is just the start. Crush it for x2, enrich it in Mekanism for x3, purify it for x4, or run the full chemical chain for up to x16.",
               "The deeper you process, the further every vein stretches. The Mekanism chapters show you how."],
         tasks=[CK("Triple an ore with a Purification Chamber")],
         rewards=[XP(150)]),
])
