name = "Gaia Awakening"
author = "VugasDev"
version = "0.3.2-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0eaeaf31a65e679a0bbb631dbae13e21e6f1025a921b31e505632229267479b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
