name = "Gaia Awakening"
author = "VugasDev"
version = "0.3.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b4e1aff89dd31a7437909683a1955b12e87c36fb55c9b1b3ee5ef4de84c0702"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
